language: php

services:
  - mysql
php:
  - 7.1

before_install:
  - cp .env.travis .env
  - composer install --dev --ignore-platform-reqs
  - php artisan key:generate
  - mysql -e 'CREATE DATABASE jss_placements;'
  - php artisan migrate

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit tests/ --coverage-clover build/logs/clover.xml
  - php vendor/bin/phpcbf --standard=ruleset.xml app/
  - php vendor/bin/phpcs --standard=ruleset.xml app/
  - php artisan self-diagnosis

after_script:
  - php vendor/bin/coveralls -v
